databases:
  - name: custom_export
    databaseName: custom_export
    user: custom_export
    plan: free

services:
  - type: web
    name: custom_export
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: custom_export
          property: "postgres://custom_export:7eIft5gaqCDHuhpIK0xSMoDuFQyUD4AK@dpg-cnfo3pocmk4c73b0le3g-a/custom_export"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default